---
title: "R Notebook"
output: html_notebook
header-includes: \usepackage{fvextra}\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---
By: Aditya Jain, Ahmed Omar, Yedu Krishnan

```{r}
library(binom)
library(car)
library(collapsibleTree)
library(dbplyr)
library(dplyr)
library(EnvStats)
library(ggplot2)
library(gmodels)
library(htmltools)
library(ISLR)
library(knitr)
library(lawstat)
library(markdown)
library(mdsr)
library(mosaicData)
library(nycflights13)
library(olsrr)
library(plyr)
library(purrr)
library(plotly)
library(resampledata)
library(rmarkdown)
library(rpart)
library(rpart.plot)
library(rvest)
library(SDaA)
library(shiny)
library(stringi)
library(tibble)
library(tidyr)
library(tidyselect)
library(tinytex)
library(yaml)
library(shiny)
library(MASS)
library(lmtest)
library(mctest)
library(GGally)
```

```{r}
data = read.csv("fuelcar.csv")

model = lm(mpg ~ factor(cylinders) + displacement + horsepower + weight + acceleration +  factor(origin), data = data)
summary(model)

```

```{r}
reducedmodel =lm(mpg ~ factor(cylinders) + horsepower + weight +  factor(origin) , data = data)
summary(reducedmodel)
```

```{r}
interacmodel =lm(mpg ~ (factor(cylinders) + horsepower + weight +  factor(origin))^2 , data = data)
summary(interacmodel)
```

```{r}
interacmodel1 = lm(mpg ~ factor(cylinders) + horsepower + weight +  factor(origin) + horsepower:origin, data = data)
summary(interacmodel1)

```


```{r}
# Stepwise Regression Procedure
stepmod=ols_step_both_p(model,pent = 0.05, prem = 0.1, details=FALSE)
summary(stepmod$model)

# Backward Elimination Procedure 
backmodel=ols_step_backward_p(model, prem = 0.1, details=FALSE) 
summary(backmodel$model)

# Forward Selection Procedure 
formodel=ols_step_forward_p(reducedmodel,penter = 0.1, details=FALSE) 
summary(formodel$model)
```



```{r}
# Linearity assumptions
ggplot(interacmodel1, aes(x=.fitted, y=.resid)) +
  geom_point() + geom_smooth()+
  geom_hline(yintercept = 0)

```

```{r}
# H0: Heteroscedasticity is not present (homoscedasticity)
# HA: Heteroscedasticity is present 
bptest(interacmodel1)


```

```{r}
# H0: The sample data are normally distributed
# HA: The sample data are NOT normally distributed

# Histogram
ggplot(data=data, aes(residuals(interacmodel1))) +
  geom_histogram(breaks = seq(-1,1,by=0.01), col="black", fill="blue") +
  labs(title="Histogram for residuals") +
  labs(x="residuals", y="Count")

# Normal QQ plot
ggplot(data = data, aes(sample=interacmodel1$residuals)) +
  stat_qq() +
  stat_qq_line()

# Shapiro Wilk test
shapiro.test(residuals(interacmodel1))

```

```{r}
# Multicollinearity

imcdiag(model, method="VIF")

```

```{r}
# Check leverage points
lev=hatvalues(interacmodel1)
p = length(coef(interacmodel1))
n = nrow(data)
outlier3p = lev[lev>(3*p/n)]
outlier3p

# Plot the outliers 
plot(rownames(data), lev, main = "Leverage in KBI Dataset", xlab = "Observation", ylab = "Leverage Value")
abline(h = 3 * p / n, lty = 1)

# Create new dataset without outliers

data_no_outliers = data[-as.numeric(names(outlier3p)), ]
data_no_outliers
newdata = data.frame(data_no_outliers)


```


```{r}
# Box-Cox Transformation
bc=boxcox(interacmodel1,lambda=seq(-1,1))

bestlambda=bc$x[which(bc$y==max(bc$y))]
bestlambda

bcmodel = lm((((mpg ^ -0.2727273)-1)/-0.2727273) ~ factor(cylinders) + horsepower + weight +  factor(origin) + horsepower:origin, data = data)

summary(bcmodel)

ggplot(data = data, aes(sample=bcmodel$residuals)) +
  stat_qq() +
  stat_qq_line()

shapiro.test(residuals(bcmodel))
bptest(bcmodel)

plot(bcmodel, which = 5)
plot(bcmodel, which = 4)

```





```{r}
interacmodel1 = lm(mpg ~ factor(cylinders) + horsepower + weight + factor(origin) + horsepower:origin, data = data)
summary(interacmodel1)

bcmodel = lm((((mpg ^ -0.2727273)-1)/-0.2727273) ~ factor(cylinders) + horsepower + weight +  factor(origin) + horsepower:origin , data = data)
summary(bcmodel)

new_data = data.frame(
  cylinders = 8,
  horsepower = 130,
  weight = 3504,
  origin = 1
)

# Predictions
prediction = predict(bcmodel, newdata = new_data, interval = "predict")
prediction
```


